-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 21:16:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Territory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Territory` (
  `Ter_shortName` VARCHAR(20) NOT NULL,
  `Ter_longName` VARCHAR(50) NULL,
  `Ter_State` CHAR(2) NOT NULL,
  `Ter_Zip4` DECIMAL(4,0) NULL,
  `Ter_Zip5` DECIMAL(5,0) NOT NULL,
  PRIMARY KEY (`Ter_shortName`),
  UNIQUE INDEX `shortName_UNIQUE` (`Ter_shortName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AuctionHouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AuctionHouse` (
  `AucHouse_name` VARCHAR(20) NOT NULL,
  `AucHouse_ETSD` DATE NOT NULL,
  `AucHouse_Footage` INT NOT NULL,
  `Auc_isIndoor` TINYINT(1) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`AucHouse_name`, `Ter_shortName`),
  UNIQUE INDEX `name_UNIQUE` (`AucHouse_name` ASC) VISIBLE,
  INDEX `fk_AuctionHouse_Territory1_idx` (`Ter_shortName` ASC) VISIBLE,
  CONSTRAINT `fk_AuctionHouse_Territory1`
    FOREIGN KEY (`Ter_shortName`)
    REFERENCES `mydb`.`Territory` (`Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seller` (
  `Sel_FirstName` VARCHAR(20) NOT NULL,
  `Sel_MiddleIntial` CHAR(1) NOT NULL,
  `Sel_LastName` VARCHAR(30) NOT NULL,
  `Zip5` DECIMAL(5,0) NOT NULL,
  `Sel_Zip4` DECIMAL(4,0) NULL,
  `Sel_MailingAddress` VARCHAR(50) NOT NULL,
  `Sel_City` VARCHAR(20) NOT NULL,
  `Sel_State` CHAR(2) NOT NULL,
  PRIMARY KEY (`Sel_FirstName`, `Sel_MiddleIntial`, `Sel_LastName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `Item_ID` INT(8) NOT NULL AUTO_INCREMENT,
  `Item_Name` TEXT(20) NOT NULL,
  `Item_ESTD` DATE NOT NULL,
  `Sel_FirstName` VARCHAR(20) NOT NULL,
  `Sel_MiddleIntial` CHAR(1) NOT NULL,
  `Sel_LastName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Item_ID`, `Sel_FirstName`, `Sel_MiddleIntial`, `Sel_LastName`),
  UNIQUE INDEX `ID_UNIQUE` (`Item_ID` ASC) VISIBLE,
  INDEX `fk_Item_Seller1_idx` (`Sel_FirstName` ASC, `Sel_MiddleIntial` ASC, `Sel_LastName` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Seller1`
    FOREIGN KEY (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    REFERENCES `mydb`.`Seller` (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auctioneer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auctioneer` (
  `Auc_FirstName` VARCHAR(20) NOT NULL,
  `Auc_MiddleIntitial` CHAR(1) NOT NULL,
  `Auc_LastName` VARCHAR(30) NOT NULL,
  `Auc_Commission` DECIMAL(2,0) NOT NULL,
  `Auc_Zip5` DECIMAL(5,0) NOT NULL,
  `Auc_Zip4` DECIMAL(4,0) NULL,
  `Auc_MailingAddress` VARCHAR(50) NOT NULL,
  `Auc_City` VARCHAR(20) NOT NULL,
  `Auc_State` CHAR(2) NOT NULL,
  PRIMARY KEY (`Auc_FirstName`, `Auc_MiddleIntitial`, `Auc_LastName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buyer` (
  `Buyer_ID` INT NOT NULL AUTO_INCREMENT,
  `Buyer_FirstName` VARCHAR(20) NOT NULL,
  `Buyer_MiddleInitial` CHAR(1) NOT NULL,
  `Buyer_LastName` VARCHAR(30) NOT NULL,
  `Buyer_Commission` DECIMAL(2,0) NOT NULL,
  `Buyer_Zip5` DECIMAL(5,0) NOT NULL,
  `Buyer_MailingAddress` VARCHAR(50) NOT NULL,
  `Buyer_City` VARCHAR(20) NOT NULL,
  `AucHouse_name` VARCHAR(20) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  `Buyer_State` CHAR(2) NOT NULL,
  `Buyer_Zip4` DECIMAL(4,0) NULL,
  PRIMARY KEY (`Buyer_ID`, `AucHouse_name`, `Ter_shortName`),
  INDEX `fk_Buyer_AuctionHouse1_idx` (`AucHouse_name` ASC, `Ter_shortName` ASC) VISIBLE,
  CONSTRAINT `fk_Buyer_AuctionHouse1`
    FOREIGN KEY (`AucHouse_name` , `Ter_shortName`)
    REFERENCES `mydb`.`AuctionHouse` (`AucHouse_name` , `Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bid` (
  `Bid_DollarAmount` DECIMAL(6,2) NOT NULL,
  `Bid_WinDate` DATETIME NULL,
  `Buyer_ID` INT NOT NULL,
  `Buyer_FirstName` VARCHAR(20) NOT NULL,
  `Buyer_MiddleInitial` CHAR(1) NOT NULL,
  `Buyer_LastName` VARCHAR(30) NOT NULL,
  `Item_ID` INT(8) NOT NULL,
  `Item_Name` TEXT(20) NOT NULL,
  `Sel_FirstName` VARCHAR(20) NOT NULL,
  `Sel_MiddleIntial` CHAR(1) NOT NULL,
  `Sel_LastName` VARCHAR(30) NOT NULL,
  `AucHouse_name` VARCHAR(20) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Bid_DollarAmount`, `Buyer_ID`, `Buyer_FirstName`, `Buyer_MiddleInitial`, `Buyer_LastName`, `Item_ID`, `Item_Name`, `Sel_FirstName`, `Sel_MiddleIntial`, `Sel_LastName`, `AucHouse_name`, `Ter_shortName`),
  INDEX `fk_Bid_Buyer1_idx` (`Buyer_ID` ASC, `Buyer_FirstName` ASC, `Buyer_MiddleInitial` ASC, `Buyer_LastName` ASC) VISIBLE,
  INDEX `fk_Bid_Item1_idx` (`Item_ID` ASC, `Item_Name` ASC, `Sel_FirstName` ASC, `Sel_MiddleIntial` ASC, `Sel_LastName` ASC) VISIBLE,
  INDEX `fk_Bid_AuctionHouse1_idx` (`AucHouse_name` ASC, `Ter_shortName` ASC) VISIBLE,
  CONSTRAINT `fk_Bid_Buyer1`
    FOREIGN KEY (`Buyer_ID` , `Buyer_FirstName` , `Buyer_MiddleInitial` , `Buyer_LastName`)
    REFERENCES `mydb`.`Buyer` (`Buyer_ID` , `Buyer_FirstName` , `Buyer_MiddleInitial` , `Buyer_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bid_Item1`
    FOREIGN KEY (`Item_ID` , `Item_Name` , `Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    REFERENCES `mydb`.`Item` (`Item_ID` , `Item_Name` , `Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bid_AuctionHouse1`
    FOREIGN KEY (`AucHouse_name` , `Ter_shortName`)
    REFERENCES `mydb`.`AuctionHouse` (`AucHouse_name` , `Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `Acc_AmountOwed` DECIMAL(6,2) NOT NULL,
  `Sel_FirstName` VARCHAR(20) NOT NULL,
  `Sel_MiddleIntial` CHAR(1) NOT NULL,
  `Sel_LastName` VARCHAR(30) NOT NULL,
  `Buyer_ID` INT NOT NULL,
  `Buyer_FirstName` VARCHAR(20) NOT NULL,
  `Buyer_MiddleInitial` CHAR(1) NOT NULL,
  `Buyer_LastName` VARCHAR(30) NOT NULL,
  `AucHouse_name` VARCHAR(20) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Acc_AmountOwed`, `Sel_FirstName`, `Sel_MiddleIntial`, `Sel_LastName`, `Buyer_ID`, `Buyer_FirstName`, `Buyer_MiddleInitial`, `Buyer_LastName`, `AucHouse_name`, `Ter_shortName`),
  INDEX `fk_Account_Seller1_idx` (`Sel_FirstName` ASC, `Sel_MiddleIntial` ASC, `Sel_LastName` ASC) VISIBLE,
  INDEX `fk_Account_Buyer1_idx` (`Buyer_ID` ASC, `Buyer_FirstName` ASC, `Buyer_MiddleInitial` ASC, `Buyer_LastName` ASC, `AucHouse_name` ASC, `Ter_shortName` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Seller1`
    FOREIGN KEY (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    REFERENCES `mydb`.`Seller` (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Buyer1`
    FOREIGN KEY (`Buyer_ID` , `Buyer_FirstName` , `Buyer_MiddleInitial` , `Buyer_LastName` , `AucHouse_name` , `Ter_shortName`)
    REFERENCES `mydb`.`Buyer` (`Buyer_ID` , `Buyer_FirstName` , `Buyer_MiddleInitial` , `Buyer_LastName` , `AucHouse_name` , `Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SellsIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SellsIn` (
  `Sel_FirstName` VARCHAR(20) NOT NULL,
  `Sel_MiddleIntial` CHAR(1) NOT NULL,
  `Sel_LastName` VARCHAR(30) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Sel_FirstName`, `Sel_MiddleIntial`, `Sel_LastName`, `Ter_shortName`),
  INDEX `fk_Seller_has_Territory_Territory1_idx` (`Ter_shortName` ASC) VISIBLE,
  INDEX `fk_Seller_has_Territory_Seller1_idx` (`Sel_FirstName` ASC, `Sel_MiddleIntial` ASC, `Sel_LastName` ASC) VISIBLE,
  CONSTRAINT `fk_Seller_has_Territory_Seller1`
    FOREIGN KEY (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    REFERENCES `mydb`.`Seller` (`Sel_FirstName` , `Sel_MiddleIntial` , `Sel_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seller_has_Territory_Territory1`
    FOREIGN KEY (`Ter_shortName`)
    REFERENCES `mydb`.`Territory` (`Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WorksIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WorksIn` (
  `Auc_FirstName` VARCHAR(20) NOT NULL,
  `Auc_MiddleIntitial` CHAR(1) NOT NULL,
  `Auc_LastName` VARCHAR(30) NOT NULL,
  `Ter_shortName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Auc_FirstName`, `Auc_MiddleIntitial`, `Auc_LastName`, `Ter_shortName`),
  INDEX `fk_Auctioneer_has_Territory_Territory1_idx` (`Ter_shortName` ASC) VISIBLE,
  INDEX `fk_Auctioneer_has_Territory_Auctioneer1_idx` (`Auc_FirstName` ASC, `Auc_MiddleIntitial` ASC, `Auc_LastName` ASC) VISIBLE,
  CONSTRAINT `fk_Auctioneer_has_Territory_Auctioneer1`
    FOREIGN KEY (`Auc_FirstName` , `Auc_MiddleIntitial` , `Auc_LastName`)
    REFERENCES `mydb`.`Auctioneer` (`Auc_FirstName` , `Auc_MiddleIntitial` , `Auc_LastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auctioneer_has_Territory_Territory1`
    FOREIGN KEY (`Ter_shortName`)
    REFERENCES `mydb`.`Territory` (`Ter_shortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
